### ISSUE TITLE
[Feature] Inspect entitys and blocks without server

### ISSUE THREAD

**Issue by davidmayr** [wisp-forest/gadget#26]
It would be awesome to be just able to inspect the local entity state that the **client knows**. 
That would make this mod so much more useful.

**Comment by BasiqueEvangelist** [comment]
Gating the client view behind the server view is intentional, as to not make the mod too cheaty:tm:. In any case, this mod is primarily a mod debugging tool, so I just assume that if you have full permission you have gadget on the server too.
I am thinking about allowing using the client view on all servers, though.

**Comment by Vap0r1ze** [comment]
I'm trying to use this plugin to understand how modern servers work, and teach myself about the minecraft protocol. This would be  super useful for me as a dev.
